# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: weatherforecast
registry: mvpconf.azurecr.io
namespace: weatherforecast
services:
- name: frontend
  project: src/frontend/frontend.csproj
  bindings:
  - port: 34200
- name: backend
  project: src/backend/backend.csproj
  bindings:
  - port: 34300
- name: mssql-server
  image: mcr.microsoft.com/mssql/server:2019-latest
  env:
    - name: "MSSQL_SA_PASSWORD"
      value: "!MySecretTemplafyPassword1"
    - name: ACCEPT_EULA
      value: "Y"
  bindings:
    - port: 1433
      connectionString: "Server=${host},${port};Database=WeatherForecast;User Id=sa;Password=${env:MSSQL_SA_PASSWORD};TrustServerCertificate=False"
